"""
Preprocessing of the input cortical surfaces and brain MRI volumes.
The goal is to establish correspondence between the input surfaces and volumes.

To reduce the GPU memory cost, we clip the input MRI volume and
translate the surfaces accordingly.

For a new dataset, if the MRI is aligned to MNI-152 space 
and the ground truth is generated by FreeSurfer,
we recommend to set data_name='adni' with slight modification on the image clipping.

Note: it is tedious to tune the transformation of the surface to match the volume
for a new dataset, but the matching is important to make everything work.
"""


import numpy as np

def process_volume(x, data_name='hcp'):

    if data_name == '5T': # caoshui 5T
        # 归一化
        x = x.astype(np.float32)
        x = x / x.max()  # 归一化到 [0,1]
        # # z-score 标准化
        # x = x.astype(np.float32)
        # x = (x - x.mean()) / (x.mean() + 1e-8)
        return x[None, ...].copy() # 或者 return x[None].copy()
    else:
        raise ValueError("data_name should be in ['hcp','adni','dhcp','5T']")


def process_surface(v, f, volume_shape, data_name='hcp'):
    f = f.astype(np.float32)
    D, H, W = volume_shape   # 提取维度
    # 归一化因子：将体素坐标 [0, D-1] 映射到 [-1, 1]
    # 注意：F.grid_sample 要求 (x,y,z) 对应 (W,H,D)
    norm_scale = np.array([W - 1, H - 1, D - 1])  # (W, H, D)

    if data_name == '5T':
        # v_tmp = np.ones([v.shape[0],4])
        # v_tmp[:,:3] = v
        # v = v_tmp.dot(np.linalg.inv(brain.affine).T)[:,:3]
        # v = v[:,[0,2,1]].copy()
        # 归一化
        v = v.astype(np.float32)  # 👈 添加这行
        v = 2 * v / norm_scale - 1
        return v, f
    else:
        raise ValueError("data_name should be in ['hcp','adni','dhcp']")

    return v, f


def process_surface_inverse(v, f, volume_shape, data_name='hcp'):
    """
    inversed preprocessing to transform the surface to its original space
    """
    D, H, W = volume_shape
    norm_scale = np.array([W - 1, H - 1, D - 1])  # (W, H, D)

    
    if data_name == '5T':
        # Step 1: [-1, 1] → 体素坐标（无偏移）
        v = (v + 1) * norm_scale / 2  # (N, 3)
        return v, f       
    else:
        raise ValueError("data_name should be in ['hcp','adni','dhcp']")

    return v, f
